### ISSUE TITLE
Identity: add method for PeerId generation

### ISSUE THREAD

**Issue by folex** [fluencelabs/trust-graph#8]
Currently users of the library need to explicitly use libp2p:
```rust
use libp2p::identity::ed25519::Keypair;

let kp = Keypair::generate();
let public_key = libp2p::identity::PublicKey::Ed25519(kp.public());
PeerId::from(public_key)
```

fluence-identity's PublicKey (maybe only ed25519, maybe all kinds of keys) must provide api to generate `libp2p::PeerId`

**Comment by folex** [comment]
It's a real struggle

**Comment by justprosh** [comment]
already added in my branch
